### ISSUE TITLE
Resolving fields for state specific edits

### ISSUE THREAD

**Issue by jpalmerpivotal** [imsweb/validation-translation#2]
When I was getting started with state metafiles I ran into issues with unmapped fields. I noticed your work with non-NAACCR fields within the MetafileTranslationDemo. Initially I was planning to mimic this behavior; however I think I came up with a better solution that you may want to incorporate as a first class behavior of the TranslationConfiguration.

Where in the demo you had:
```
conf.setFieldResolver(new FieldResolver() {
            @Override
            protected String resolveFieldPostDictionary(MetafileField field, TranslationConfiguration conf) {
                String propName = super.resolveFieldPostDictionary(field, conf);
                if (propName != null)
                    return propName;

                int itemNumber = field.getNumber();

                if (itemNumber == 10060)
                    return "eodOld4DigitExtent";
                if (itemNumber == 10070)
                    return "eodOld4DigitNodes";
                if (itemNumber == 10080)
                ...
```

I decided to try and leverage the State XML User Dictionaries. So for PA State metafile it would look something like:
```
int itemNumber = field.getNumber();

File dictFile = new File("PA/PA-UserDefinedDictionary-v22.xml");
try {
      NaaccrDictionary userDict = NaaccrXmlDictionaryUtils.readDictionary(dictFile);
      NaaccrDictionaryItem item = userDict.getItemByNaaccrNum(itemNumber);

      if (item != null) {
                return item.getNaaccrId();
      }
} catch (IOException e) {
      System.out.println("Failed to read dict with error: " + e);
}
```

I may be missing something, but it seems to me that being able to pass in a User Dictionary to supplement the NAACCR dictionary could be valuable. 

For now I have my own approach that is working leveraging the dependency injection you provided, but I wanted to raise the idea to your attention.

**Comment by depryf** [comment]
Yes, being able to provide one or several user-defined dictionary sounds like a good improvement, and it shouldn't be very complicated. I will see what I can do to add support for that.

Note that for this to work, the user-defined dictionary need to use the same NAACCR Item numbers as the metafile. It's probably the case already since the metafile usually allow the non-standard fields to be created by importing a user-defined dictionary, so that should be fine.

**Comment by depryf** [comment]
The configuration now accepts a list of dictionaries:

```java
conf.setUserDefinedDictionaries(Collections.singletonList(dictionary));
```

If provided, the default field resolver will use that to resolve items that can't be resolved from the base dictionary.

The matching is done using the NAACCR numbers (the same as with the base dictionary).

The user-defined dictionaries need to have the same NAACCR version as the one provided in the configuration, or they need to have no version (which means they support all NAACCR versions).

**Comment by jpalmerpivotal** [comment]
Looks wonderful, very convenient for my workflow. Thanks!
