### ISSUE TITLE
"Unable to parse" non-breaking error message

### ISSUE THREAD

**Issue by jpalmerpivotal** [imsweb/validation-translation#3]
When I run the basic NAACCR v22 metafile `NAACCR_v22A_20210920_XML_layout.smf` I get the error message 
`!!! Unable to parse 'Autopsy Only, RX, Schema ID, Primary Site, 2018 (NPCR)': class com.imsweb.validation.translation.language.entity.IfThenElseStatement cannot be cast to class com.imsweb.validation.translation.language.entity.ParsedTree (com.imsweb.validation.translation.language.entity.IfThenElseStatement and com.imsweb.validation.translation.language.entity.ParsedTree are in unnamed module of loader 'app')`
Which reads to me as though the edit will be non-functional.
in the translated edits XML I see a comment `// This edit could not be translated because it contains invalid syntax.`
And in the groovy:
```
    public boolean NAA2202230(Binding binding, Map<String, Object> context, MetafileContextFunctions functions, List<Map<String, String>> untrimmedlines, Map<String, String> untrimmedline) throws Exception {
        // This edit could not be translated because it contains invalid syntax.
        
        return true

    }
 ```
 I was surprised that it passed with an edit failing. But the other issue that I found concerning was that the error message was emitted before 1000's of lines of output and towards the end I see the message `  > no edit got removed` which to me it felt like having an edit just return `true` would be equivalent to removing it.
 So I think separate from the fact the translation failed, the messaging around the edits that are skipped should be more prominent in the final results summary. While I agree creating a whole `failed-translation-...` file is a pretty clear signal, it wasn't immediately clear to me from the output in the terminal. 
 Potentially there could be an option to fail if any edits can't be parsed but that may be overkill.

**Comment by depryf** [comment]
Sometimes a metafile contains syntax issues and the translation can't happen. 

In that case the logic returns true so the edits always pass (that's the least intrusive way to deal with this).

I agree with you that those translation errors are hidden in the logs (personally I know where they tend to happen and I usually stare at the logs and can determine right away if everything was good or not, but this is not a good excuse).

I will change that so something obvious is printed at the ends when some edits didn't translate properly.

PS - the "no edit got removed" just means that no edit got removed between one version of a translated metafile and the next version. It's not related to whether an edit can be translated or not.
