### ISSUE TITLE
Unable to parse: Unable to translate regex '        '

### ISSUE THREAD

**Issue by jpalmerpivotal** [imsweb/validation-translation#9]
It appears that Pennsylvania is using space characters as literals and it is trying to convert to a regex. I am not sure if the metafile is doing this the correct way but that is what I am seeing. 

Effected edits for this issue (only Pennsylvania): 

- `PA2552`:`Z_Date of Inpt Disch, Date of 1st Contact`
- `PA2568`:`Z_Institution Referred From`
- `PA2581`:`Z_Primary Site, Behavior Code ICDO2`
- `PA2582`:`Z_Primary Site, Behavior Code ICDO3`
- `PA2591`:`Z_Reg Nodes, Date of DX`
- `PA2602`:`Z_Summary Stage 77, Date of Diagnosis`

Example Failure:
```
PA2552
/** Z_Date of Inpt Disch, Date of 1st Contact */
If (MATCH(#S"Date of 1st Contact", "        "))
    return pass;
else
    If (!MATCH(#S"Date of Inpt Disch", "        ") And
```
```
PA2568
If (Match(#S"Institution Referred From", "          "))
```
```
PA2581
If (Match(#S"Behavior (92-00) ICD-O-2", " "))
    Return Pass;
```

**Comment by depryf** [comment]
This is weird; clearly the intend is to check that the value is all spaces, but that's not the expected way to do it since there is an "EMPTY" method for that.

This being said, I think it will be simple to translate an "all-spaces" regex to a "\s+".

**Comment by depryf** [comment]
This should work now.
